[book]
authors = ["j-awada"]
language = "en"
src = "src"
title = "AWS Certified DevOps Engineer Professional"
[output.html]
site-url = "/aws-dop-c02-prep/"
number-chapters = false
additional-css = ["theme/custom.css"]